config/routes.rb
VpontisStubailoDsessomsSanthoshnarayanFinal::Application.routes.draw do
  devise_for :players

  resources :games, :only => [:new, :create, :index, :show, :destroy] do
    post 'confirm', on: :member
    get "confirmations", on: :collection
  end

  resources :players, :only => [:show, :index]
  resources :groups do
    post 'add_player', on: :member
  end

  get "/help", to: "pages#help"
  get "/about", to: "pages#about"
  root 'pages#dashboard'

  

end

app/models/group.rb
class Group < ActiveRecord::Base

  ###############################################
  # VALIDATION AND HOOKS                        #
  ###############################################

  validates :name, presence: true
  validates_uniqueness_of :name, case_sensitive: false

  def self.global
    Group.find_by(name: 'Global')
  end

  ###############################################
  # IMAGES                                      #
  ###############################################

  has_attached_file :image, :styles => {:full_width => "1170x200#", :thumb => "400x70#"}

  ###############################################
  # PLAYERS                                     #
  ###############################################

  # players
  has_many :group_players
  has_many :players, through: :group_players, source: 'player'

  belongs_to :admin, class_name: "Player", foreign_key: "admin_id"

  def player_usernames
    self.players.map {|p| p.username}
  end

  def add_player_by_username(username)
    player = Player.find_by(username: username)

    if player.nil? 
      errors.add(:players, "#{username} not found.")
      false
    elsif self.player_usernames.include? username
      errors.add(:players, "#{username} already in group.")
      false
    else
      self.players << player
    end
  end

  def ranked_players
    return players.sort {|a,b| b.points_in(self) <=> a.points_in(self) }
  end

  ###############################################
  # GAMES                                       #
  ###############################################

  has_many :group_games
  has_many :games, through: :group_games, source: 'game'

  # transfers points for group players in a game
  def transfer_points(game)
    group_game_winners = game.winners.map {|winner| self.group_players.find_by(player_id: winner.id)}
    group_game_losers = game.losers.map {|loser| self.group_players.find_by(player_id: loser.id)}

    winner_ratings = group_game_winners.map {|g| g.points }
    loser_ratings = group_game_losers.map {|g| g.points }

    point_change = Game.point_change(winner_ratings, loser_ratings)
    
    group_game_winners.each do |winner|
      winner.points += point_change
      winner.games_count += 1
      winner.save
    end
    group_game_losers.each do |loser|
      loser.points -= point_change
      loser.games_count += 1
      loser.save
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :set_group, only: [:show, :update, :edit, :add_player, :destroy]
  authorize_resource

  def index
    @groups = Group.accessible_by(current_ability)
    @player = current_player
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.admin = current_player
    @group.players << current_player

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_path(@group) }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_player
    username = params[:username]

    respond_to do |format|
      if @group.add_player_by_username(username)
        format.html { redirect_to @group, notice: 'Player successfully added to group.' }
        format.json { head :no_content }
      else
        format.html { redirect_to @group, notice: @group.errors.full_messages.first }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @group.update(group_params)
      redirect_to group_path(@group), notice: 'Group was successfully updated.'  
    else
      render action: 'edit' 
    end
  end

  def show
    @players = @group.ranked_players
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to :root }
      format.json { head :no_content }
    end
  end

  private
    def group_params
      params.require(:group).permit(:name, :image)
    end

    def set_group
      @group = Group.find(params[:id])
    end
end 

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_add_player_form.html.haml
.group-add-player-form
  = form_tag add_player_group_path(@group), method: 'post', class: "form-inline" do |f| 
    - if @group.errors.any? 
      #error_explanation
        %h2 #{pluralize(@group.errors.count, "error")} prohibited this group from being saved:

        %ul
          - @group.errors.full_messages.each do |msg| 
            %li= msg

    .form-group
      = text_field_tag "username", '', placeholder: 'username', class: 'form-control player-input'

    = submit_tag 'Add Player', :class => "btn btn-primary"

app/views/groups/_form.html.haml
= form_for(@group) do |f| 
  - if @group.errors.any? 
    #error_explanation
      %h2 #{pluralize(@group.errors.count, "error")} prohibited this group from being saved:

      %ul
        - @group.errors.full_messages.each do |msg| 
          %li= msg



  .form-group
    = f.label :name, "Group Name"
    = f.text_field :name, placeholder: 'name', class: 'form-control'
  .form-group
    = f.label :image, "Banner Image"
    = f.file_field :image
    %p.help-block
      This image will be cropped to 1170x200 pixels to fit in the banner at the top of your group's page.

  .actions
    = f.submit :class => "btn btn-primary", :value => "Save Group" 

app/views/groups/_group.html.haml
.group-mini
  - background = group.image.exists? ? ("url(" + URI.join(request.url, group.image.url(:thumb)).to_s + ")") : ""
  .group-mini-header{:style => "background: #{background}"}
    = link_to group.name, group
  .group-mini-content
    #{@player.username} is ranked #{@player.rank_in(group)} with #{number_with_precision(@player.points_in(group), precision: 0)} points.

app/views/groups/edit.html.haml
%h1 Edit Group

= render 'form'

app/views/groups/index.html.haml
%h1 Groups You're In
%ul.shared-groups.list-unstyled
  - @groups.each do |group|
    %li
    = render partial: "groups/group", object: group
  
= link_to "New Group", new_group_path, :class => "btn btn-success"

app/views/groups/new.html.haml
%h1 New Group

%p
  Make a group and get ranked against your friends!
%p
  Any games you play with other group members after the group is created will contribute to your ranking in this group.

= render 'form'

app/views/groups/show.html.haml
- background = @group.image.exists? ? ("url(" + URI.join(request.url, @group.image.url(:full_width)).to_s + ")") : ""
.group-header-image{:style => "background: #{background}"}
  
  .group-admin-links.hidden-xs
    - if can? :update, @group
      You're the administrator!
      %ul.list-inline
        %li= link_to "Edit Group", edit_group_path(@group)
        %li= link_to "Delete Group", group_path(@group), :method => "delete", :confirm => "Are you sure you want to delete the group \"#{@group.name}\"? This cannot be undone."
    - else
      Administrator:
      = link_to @group.admin.username, @group.admin, :class => "player-link"

  %h1 #{@group.name}
  
%br.visible-xs
%ul.nav.nav-tabs.visible-xs.group-tabs
  %li.active
    %a{:href => "#players", :"data-toggle" => "tab"} Player Rankings
  %li
    %a{:href => "#games", :"data-toggle" => "tab"} Game Feed
.row.tab-content
  .col-sm-6.tab-pane.active#players
    %h3.hidden-xs Players
    %br.visible-xs
    = render partial: 'players/ranking', locals: { players: @players }
    - if can? :add_player, @group
      = render 'add_player_form'
  .col-sm-6.tab-pane#games
    %h3.hidden-xs Games
    %br.visible-xs
    .games
      - @group.games.each do |game|
        = render "games/game", game: game