config/routes.rb
VpontisStubailoDsessomsSanthoshnarayanFinal::Application.routes.draw do
  devise_for :players

  resources :games, :only => [:new, :create, :index, :show, :destroy] do
    post 'confirm', on: :member
    get "confirmations", on: :collection
  end

  resources :players, :only => [:show, :index]
  resources :groups do
    post 'add_player', on: :member
  end

  get "/help", to: "pages#help"
  get "/about", to: "pages#about"
  root 'pages#dashboard'

  

end

app/models/game.rb
class Game < ActiveRecord::Base

  #returns true if a game has been confirmed by either loser
  def confirmed?
    self.confirmed
  end

  # checks if points have been transferred, after transfer this is set to true
  # and points won't be transferred again
  @transferred = false

  #confirms game
  def confirm
    self.confirmed=true

    self.groups_in_common.each do |group|
      group.transfer_points self
      group.games << self
    end

    self.save
  end

  ###############################################
  # VALIDATION AND HOOKS                        #
  ###############################################

  # validation
  validate :all_users_found
  validate :users_are_unique
 
  validates :winners, length: {is: 2, message: "should have 2 players."}
  validates :losers, length: {is: 2, message: "should have 2 players."}

  ###############################################
  # GROUPS                                      #
  ###############################################

  has_many :group_games
  has_many :groups, through: :group_games, source: 'group'

  ###############################################
  # PLAYERS                                     #
  ###############################################

  # winners
  has_many :game_winners
  has_many :winners, :through => :game_winners, :source => "player"

  # losers
  has_many :game_losers
  has_many :losers, :through => :game_losers, :source => "player"

  
  def players
    return winners + losers
  end

  # getting and setting lists of usernames
  def winner_usernames
    return winners.map {|p| p.username}
  end

  # winner usernames and loser usernames need to both be valid on time of save
  def winner_usernames=(usernames)
    @winner_usernames = usernames
    self.winners = Player.where(:username => usernames)
  end
  
  def loser_usernames
    return losers.map {|p| p.username}
  end
  
  def loser_usernames=(usernames)
    @loser_usernames = usernames
    self.losers = Player.where(:username => usernames)
  end

  def self.point_change(winner_ratings, loser_ratings)
    winners_rating = winner_ratings.sum/winner_ratings.count
    losers_rating = loser_ratings.sum/loser_ratings.count

    q_winners = 10**(winners_rating/400)
    q_losers = 10**(losers_rating/400)

    expected_winners = q_winners/(q_winners + q_losers)

    return 32*(1 - expected_winners)
  end

  def groups_in_common
    groups = self.winners[0].groups
    groups = self.winners[1].groups & groups
    groups = self.losers[0].groups & groups
    groups = self.losers[1].groups & groups
    
    groups
  end

  private
    def all_users_found
      total_not_found = []

      if @winner_usernames
        total_not_found += @winner_usernames - winner_usernames
      end
      if @loser_usernames
        total_not_found += @loser_usernames - loser_usernames
      end

      if total_not_found.any?
        errors.add(:players, total_not_found.join(", ") + " not found.")
      end
    end

    def users_are_unique
      temp_players = winners + losers
      unless temp_players.count == temp_players.uniq.count
        errors.add(:players, "can't contain duplicates")
      end
    end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy, :confirm]
  authorize_resource

  # GET /games
  # GET /games.json
  def index
    @games = Game.where(confirmed: true).order('created_at DESC').paginate(page: params[:page])
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # GET /games/confirmations
  def confirmations
    @games_to_confirm = current_player.games_to_confirm
    @pending_games = current_player.pending_games
  end

  # POST /games/1/confirm
  def confirm
    if @game.losers.include? current_player
      @game.confirm
    end

    respond_to do |format|
      format.html { redirect_to @game }
      format.json { render json: @game }
    end
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to games_path, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to confirmations_games_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:winner_usernames => [], :loser_usernames => [])
    end
end

app/helpers/games_helper.rb
module GamesHelper
  def today(games)
    games.select {|g| g.created_at > 1.day.ago}
  end

  def this_week(games)
    games.select {|g| g.created_at >= 1.week.ago and g.created_at <= 1.day.ago}
  end

  def before_this_week(games)
    games.select {|g| g.created_at < 1.week.ago}
  end

 
  end

app/views/games/_feed.html.haml
- games_today = today(@games)
- games_this_week = this_week(@games)
- games_before_this_week = before_this_week(@games)

- if not games_today.empty? 
  %h3 Last 24 Hours
  .games
    = render partial: "game", collection: games_today

-if not games_this_week.empty? 
  %h3 This Week
  .games
    = render partial: "game", collection: games_this_week

- if not games_before_this_week.empty? 
  %h3 Older
  .games
    = render partial: "game", collection: games_before_this_week

= will_paginate @games, renderer: BootstrapPagination::Rails

app/views/games/_form.html.haml
= form_for(@game) do |f| 
  - if @game.errors.any? 
    #error_explanation.alert.alert-danger
      %h4 Please fix the #{pluralize(@game.errors.count, "problem")} below and submit again:

      %ol
        - @game.errors.full_messages.each do |msg| 
          %li= msg

  .row
    .col-md-6
      %h4 Winners
      .form-group
        = text_field_tag "game[winner_usernames][]", @game.winner_usernames[0], :placeholder => "username", :class => "form-control player-input"
      .form-group
        = text_field_tag "game[winner_usernames][]", @game.winner_usernames[1], :placeholder => "username", :class => "form-control player-input"

    .col-md-6
      %h4 Losers
      .form-group
        = text_field_tag "game[loser_usernames][]", @game.loser_usernames[0], :placeholder => "username", :class => "form-control player-input"
      .form-group
        = text_field_tag "game[loser_usernames][]", @game.loser_usernames[1], :placeholder => "username", :class => "form-control player-input"

  .actions
    = f.submit :class => "btn btn-primary", :value => "Save Game" 

app/views/games/_game.html.haml
.game{:id => "game-#{game.id}"}
  - highlight ||= @player
  - if not game.confirmed? and can? :confirm, game
    .confirmation
      .btn-group
        = link_to "Confirm Game", confirm_game_path(game), :class => "btn btn-success btn-sm game-confirmation-button", :"data-hide" => "#game-#{game.id}", :method => "post"
        = link_to "Deny", game_path(game), :class => "btn btn-danger btn-sm game-confirmation-button", :"data-hide" => "#game-#{game.id}", :method => "delete"
  .results
    = game.winners.map {|player| link_to player.username, player, class: "player-link"}.join(" & ").html_safe
    beat
    = game.losers.map {|player| link_to player.username, player, class: "player-link"}.join(" & ").html_safe
  .game-time.local-time
    = game.created_at.to_i

app/views/games/confirmations.html.haml
%h1 Confirmations

.row
  .col-sm-6
    %h3 Games to Confirm
    %p Please confirm or deny whether these games happened.

    - if @games_to_confirm.any?
      .games
        - @games_to_confirm.each do |game|
          = render partial: "game", object: game
    - else
      .well
        You're all done!

  .col-sm-6
    %h3 Pending Games
    %p These are games that the losers have not yet confirmed.

    - if @pending_games.any? 
      .games
        - @pending_games.each do |game|
          = render partial: "game", object: game

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.haml
%h1 Game Feed

.game-feed
  = render partial: "feed"

app/views/games/new.html.haml
%h1 Add Game

%p After a game is added, it needs to be confirmed by one of the losers before it is visible to everyone else and contributes to the ranking.

.game-form
  = render 'form'

app/views/games/show.html.haml
.show-game-page
  .row
    %h2.col-md-8
      Game From
      %span.local-time= @game.created_at.to_i
    .col-md-4
      .game-confirmation-status
        - if @game.confirmed?
          %span.glyphicon.glyphicon-ok
          %span Game Confirmed
        - else
          %span Game Unconfirmed
          - if can? :confirm, @game
            = link_to "Confirm Game", confirm_game_path(@game), :method => "post", :class => "btn btn-primary"

  %table.table.game-page-table
    %tr
      %th
        Winners
      %th
        Losers
    %tr
      -# winner 1
      - player = @game.winners[0]
      %td
        %strong= link_to player.username, player
      -#loser 1
      - player = @game.losers[0]
      %td
        %strong= link_to player.username, player
    %tr
      -# winner 2
      - player = @game.winners[1]
      %td
        %strong= link_to player.username, player
      -#loser 2
      - player = @game.losers[1]
      %td
        %strong= link_to player.username, player