config/routes.rb
VpontisStubailoDsessomsSanthoshnarayanFinal::Application.routes.draw do
  devise_for :players

  resources :games, :only => [:new, :create, :index, :show, :destroy] do
    post 'confirm', on: :member
    get "confirmations", on: :collection
  end

  resources :players, :only => [:show, :index]
  resources :groups do
    post 'add_player', on: :member
  end

  get "/help", to: "pages#help"
  get "/about", to: "pages#about"
  root 'pages#dashboard'

  

end

app/views/layouts/_footer.html.haml
.footer
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-45891296-1', 'rerack.me');
    ga('send', 'pageview');


  %p
    #{link_to 'about', '/about'} | #{link_to 'help', '/help'} | #{link_to 'code on github', 'https://www.github.com/vpontis/rerack.me'}

app/views/layouts/application.html.haml
!!! html
%html
  %head
    %title rerack.me
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic'
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    %meta{:name => "viewport", :content => "width=device-width, user-scalable=no"}
    = csrf_meta_tags
%body{:class => current_player ? "logged-in" : "logged-out"}
  - if current_player
    .container
      %nav.navbar.navbar-default.navbar-fixed-top
        .container
          .navbar-header
            %button.navbar-toggle{:type => "button", :"data-toggle" => "collapse", :"data-target" => ".navbar-collapse"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            = link_to root_path, :class => "navbar-brand" do
              = image_tag "logo.svg", :class => "navbar-logo"
              .navbar-brand-text
                .title rerack.me
                .subtitle
                  %span.glyphicon.glyphicon-home{:style => "margin-right: 2px; font-size: 0.9em; top: 0"}
                  Dashboard
              
            .visible-xs.pull-right
              = link_to new_game_path, :class => "collapsed-navbar-new-game btn-navbar btn" do
                %span.glyphicon.glyphicon-plus
                Add Game
          .collapse.navbar-collapse
            %ul.nav.navbar-nav
              %li.dropdown
                = link_to "#", :class => "dropdown-toggle", :"data-toggle" => "dropdown" do
                  Go to Group
                  %b.caret
                %ul.dropdown-menu
                  - current_player.groups.each do |group|
                    %li
                      = link_to group do
                        = group.name
                  %li.divider
                  %li
                    = link_to new_group_path do
                      New Group

            %ul.nav.navbar-nav.navbar-right
              %li.hidden-xs
                = link_to new_game_path do
                  %span.glyphicon.glyphicon-plus
                  Add Game
              %li
                - if current_player.games_to_confirm.count == 0
                  - hide_game_confirmations = true
                = link_to confirmations_games_path, :class => hide_game_confirmations ? "hidden game-confirmations" : "game-confirmations" do
                  Confirm
                  .notification-count
                    = current_player.games_to_confirm.count
              %li
                = link_to current_player do
                  %span.glyphicon.glyphicon-user
                  = current_player.username
              %li
                = link_to destroy_player_session_path, :method => "DELETE" do
                  %span.glyphicon.glyphicon-log-out
                  Sign Out
  - else # not logged in
    .hero
      .container
        .row
          .col-sm-4.text-center
            = image_tag "logo.svg"
            %h1
              rerack.me
            %p The best pong player ranking system.
          .col-sm-7.col-sm-offset-1
            %br
            %h3 1. sign up and see your friends' results
            %h3 2. record your own games for posterity
            %h3 3. get ranked
            %h3 4. experience eternal glory
          
  .container.page
    - flash.each do |key, value|
      - case key.to_s
      - when "notice"
        - alert_class = "success"
      - when "error"
        - alert_class = "danger"
      - else
        - alert_class = "info"
      .alert{:class => "alert-#{alert_class} alert-flash"}
        = value

    = yield
    
    = render 'layouts/footer'